apiVersion: builtin
kind: PatchTransformer
metadata:
  name: boxxkite-dev-cluster-scope-binding
patch: |-
  - op: remove
    path: /metadata/namespace
target:
  group: admissionregistration.k8s.io
  version: v1
  kind: ValidatingAdmissionPolicyBinding
  name: boxxkite-dev-sandbox-pod-hardening-binding
