"""baseline

Revision ID: 8d1eeb33637d
Revises: 
Create Date: 2026-07-14 00:10:32.508651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d1eeb33637d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('github_id', sa.String(length=64), nullable=True),
    sa.Column('google_id', sa.String(length=64), nullable=True),
    sa.Column('sso_provider_user_id', sa.String(length=191), nullable=True),
    sa.Column('sso_organization_id', sa.String(length=191), nullable=True),
    sa.Column('sso_connection_id', sa.String(length=191), nullable=True),
    sa.Column('scim_directory_user_id', sa.String(length=191), nullable=True),
    sa.Column('scim_deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('custom_allowed_commands', sa.JSON(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_index(op.f('ix_accounts_github_id'), 'accounts', ['github_id'], unique=True)
    op.create_index(op.f('ix_accounts_google_id'), 'accounts', ['google_id'], unique=True)
    op.create_index(op.f('ix_accounts_scim_directory_user_id'), 'accounts', ['scim_directory_user_id'], unique=True)
    op.create_index(op.f('ix_accounts_sso_connection_id'), 'accounts', ['sso_connection_id'], unique=False)
    op.create_index(op.f('ix_accounts_sso_organization_id'), 'accounts', ['sso_organization_id'], unique=False)
    op.create_index(op.f('ix_accounts_sso_provider_user_id'), 'accounts', ['sso_provider_user_id'], unique=True)
    op.create_table('oauth_clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=False),
    sa.Column('redirect_uris', sa.JSON(), nullable=False),
    sa.Column('client_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_clients_client_id'), 'oauth_clients', ['client_id'], unique=True)
    op.create_table('rate_limit_windows',
    sa.Column('key', sa.String(length=300), nullable=False),
    sa.Column('window_start', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key', 'window_start')
    )
    op.create_table('revoked_preview_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index('ix_revoked_preview_tokens_expires_at', 'revoked_preview_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_revoked_preview_tokens_session_id'), 'revoked_preview_tokens', ['session_id'], unique=False)
    op.create_table('admin_access_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_account_id', sa.String(length=36), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_access_log_admin_account_id'), 'admin_access_log', ['admin_account_id'], unique=False)
    op.create_index('ix_admin_access_log_admin_created', 'admin_access_log', ['admin_account_id', 'created_at'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('prefix', sa.String(length=64), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_account_id'), 'api_keys', ['account_id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_verification_tokens_account_created', 'email_verification_tokens', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_account_id'), 'email_verification_tokens', ['account_id'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_token_hash'), 'email_verification_tokens', ['token_hash'], unique=True)
    op.create_table('mcp_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('catalog_id', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'label', name='uq_mcp_connections_account_label')
    )
    op.create_index('ix_mcp_connections_account_created', 'mcp_connections', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_mcp_connections_account_id'), 'mcp_connections', ['account_id'], unique=False)
    op.create_table('oauth_authorization_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('redirect_uri', sa.String(length=2048), nullable=False),
    sa.Column('code_challenge', sa.String(length=128), nullable=False),
    sa.Column('code_challenge_method', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.String(length=200), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_oauth_auth_codes_expires_at', 'oauth_authorization_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_oauth_authorization_codes_account_id'), 'oauth_authorization_codes', ['account_id'], unique=False)
    op.create_index(op.f('ix_oauth_authorization_codes_client_id'), 'oauth_authorization_codes', ['client_id'], unique=False)
    op.create_index(op.f('ix_oauth_authorization_codes_code'), 'oauth_authorization_codes', ['code'], unique=True)
    op.create_table('oauth_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotated_from', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rotated_from'], ['oauth_tokens.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_oauth_tokens_account_created', 'oauth_tokens', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_account_id'), 'oauth_tokens', ['account_id'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_client_id'), 'oauth_tokens', ['client_id'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_refresh_token_hash'), 'oauth_tokens', ['refresh_token_hash'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_password_reset_tokens_account_created', 'password_reset_tokens', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_account_id'), 'password_reset_tokens', ['account_id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refresh_tokens_account_created', 'refresh_tokens', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_account_id'), 'refresh_tokens', ['account_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('sandbox_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('base', sa.String(length=64), nullable=False),
    sa.Column('python_packages', sa.JSON(), nullable=False),
    sa.Column('apt_packages', sa.JSON(), nullable=False),
    sa.Column('npm_packages', sa.JSON(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('digest', sa.String(length=128), nullable=True),
    sa.Column('registry_ref', sa.String(length=500), nullable=True),
    sa.Column('scan_result', sa.JSON(), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sandbox_images_account_cache_key', 'sandbox_images', ['account_id', 'cache_key', 'status'], unique=False)
    op.create_index('ix_sandbox_images_account_created', 'sandbox_images', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_sandbox_images_account_id'), 'sandbox_images', ['account_id'], unique=False)
    op.create_index(op.f('ix_sandbox_images_cache_key'), 'sandbox_images', ['cache_key'], unique=False)
    op.create_table('sandbox_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('pod_name', sa.String(length=255), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('destroyed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('destroyed_reason', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sandbox_sessions_account_active', 'sandbox_sessions', ['account_id', 'destroyed_at'], unique=False)
    op.create_index(op.f('ix_sandbox_sessions_account_id'), 'sandbox_sessions', ['account_id'], unique=False)
    op.create_table('sandbox_volumes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('size_gb', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('pvc_name', sa.String(length=200), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sandbox_volumes_account_created', 'sandbox_volumes', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_sandbox_volumes_account_id'), 'sandbox_volumes', ['account_id'], unique=False)
    op.create_table('secrets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ciphertext', sa.String(), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('wrapped_data_key', sa.String(), nullable=False),
    sa.Column('encryption_key_id', sa.String(length=200), nullable=False),
    sa.Column('allowed_hosts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'name', name='uq_secrets_account_name')
    )
    op.create_index('ix_secrets_account_created', 'secrets', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_secrets_account_id'), 'secrets', ['account_id'], unique=False)
    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('event_types', sa.JSON(), nullable=False),
    sa.Column('ciphertext', sa.String(), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('wrapped_data_key', sa.String(), nullable=False),
    sa.Column('encryption_key_id', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('payload_format', sa.String(length=32), nullable=False),
    sa.Column('hec_token_ciphertext', sa.String(), nullable=True),
    sa.Column('hec_token_nonce', sa.String(length=64), nullable=True),
    sa.Column('hec_token_wrapped_data_key', sa.String(), nullable=True),
    sa.Column('hec_token_encryption_key_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_subscriptions_account_created', 'webhook_subscriptions', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_webhook_subscriptions_account_id'), 'webhook_subscriptions', ['account_id'], unique=False)
    op.create_table('exec_log_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('output_truncated', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sandbox_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exec_log_entries_account_id'), 'exec_log_entries', ['account_id'], unique=False)
    op.create_index(op.f('ix_exec_log_entries_session_id'), 'exec_log_entries', ['session_id'], unique=False)
    op.create_index('ix_exec_log_entries_session_started', 'exec_log_entries', ['session_id', 'started_at'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('storage_key_prefix', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sandbox_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snapshots_account_created', 'snapshots', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_snapshots_account_id'), 'snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_snapshots_session_id'), 'snapshots', ['session_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_body_truncated', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['webhook_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_account_id'), 'webhook_deliveries', ['account_id'], unique=False)
    op.create_index('ix_webhook_deliveries_status_next_attempt', 'webhook_deliveries', ['status', 'next_attempt_at'], unique=False)
    op.create_index('ix_webhook_deliveries_subscription_created', 'webhook_deliveries', ['subscription_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_subscription_id'), 'webhook_deliveries', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_deliveries_subscription_id'), table_name='webhook_deliveries')
    op.drop_index('ix_webhook_deliveries_subscription_created', table_name='webhook_deliveries')
    op.drop_index('ix_webhook_deliveries_status_next_attempt', table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_account_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_snapshots_session_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_account_id'), table_name='snapshots')
    op.drop_index('ix_snapshots_account_created', table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index('ix_exec_log_entries_session_started', table_name='exec_log_entries')
    op.drop_index(op.f('ix_exec_log_entries_session_id'), table_name='exec_log_entries')
    op.drop_index(op.f('ix_exec_log_entries_account_id'), table_name='exec_log_entries')
    op.drop_table('exec_log_entries')
    op.drop_index(op.f('ix_webhook_subscriptions_account_id'), table_name='webhook_subscriptions')
    op.drop_index('ix_webhook_subscriptions_account_created', table_name='webhook_subscriptions')
    op.drop_table('webhook_subscriptions')
    op.drop_index(op.f('ix_secrets_account_id'), table_name='secrets')
    op.drop_index('ix_secrets_account_created', table_name='secrets')
    op.drop_table('secrets')
    op.drop_index(op.f('ix_sandbox_volumes_account_id'), table_name='sandbox_volumes')
    op.drop_index('ix_sandbox_volumes_account_created', table_name='sandbox_volumes')
    op.drop_table('sandbox_volumes')
    op.drop_index(op.f('ix_sandbox_sessions_account_id'), table_name='sandbox_sessions')
    op.drop_index('ix_sandbox_sessions_account_active', table_name='sandbox_sessions')
    op.drop_table('sandbox_sessions')
    op.drop_index(op.f('ix_sandbox_images_cache_key'), table_name='sandbox_images')
    op.drop_index(op.f('ix_sandbox_images_account_id'), table_name='sandbox_images')
    op.drop_index('ix_sandbox_images_account_created', table_name='sandbox_images')
    op.drop_index('ix_sandbox_images_account_cache_key', table_name='sandbox_images')
    op.drop_table('sandbox_images')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_account_id'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_account_created', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_account_id'), table_name='password_reset_tokens')
    op.drop_index('ix_password_reset_tokens_account_created', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_oauth_tokens_refresh_token_hash'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_client_id'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_account_id'), table_name='oauth_tokens')
    op.drop_index('ix_oauth_tokens_account_created', table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_oauth_authorization_codes_code'), table_name='oauth_authorization_codes')
    op.drop_index(op.f('ix_oauth_authorization_codes_client_id'), table_name='oauth_authorization_codes')
    op.drop_index(op.f('ix_oauth_authorization_codes_account_id'), table_name='oauth_authorization_codes')
    op.drop_index('ix_oauth_auth_codes_expires_at', table_name='oauth_authorization_codes')
    op.drop_table('oauth_authorization_codes')
    op.drop_index(op.f('ix_mcp_connections_account_id'), table_name='mcp_connections')
    op.drop_index('ix_mcp_connections_account_created', table_name='mcp_connections')
    op.drop_table('mcp_connections')
    op.drop_index(op.f('ix_email_verification_tokens_token_hash'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_account_id'), table_name='email_verification_tokens')
    op.drop_index('ix_email_verification_tokens_account_created', table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_account_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index('ix_admin_access_log_admin_created', table_name='admin_access_log')
    op.drop_index(op.f('ix_admin_access_log_admin_account_id'), table_name='admin_access_log')
    op.drop_table('admin_access_log')
    op.drop_index(op.f('ix_revoked_preview_tokens_session_id'), table_name='revoked_preview_tokens')
    op.drop_index('ix_revoked_preview_tokens_expires_at', table_name='revoked_preview_tokens')
    op.drop_table('revoked_preview_tokens')
    op.drop_table('rate_limit_windows')
    op.drop_index(op.f('ix_oauth_clients_client_id'), table_name='oauth_clients')
    op.drop_table('oauth_clients')
    op.drop_index(op.f('ix_accounts_sso_provider_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_sso_organization_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_sso_connection_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_scim_directory_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_google_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_github_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
