"""add trust_tier to secrets

Revision ID: e419cdafd64d
Revises: 8d1eeb33637d
Create Date: 2026-07-15 02:54:14.262827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e419cdafd64d'
down_revision: Union[str, Sequence[str], None] = '8d1eeb33637d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secrets', sa.Column('trust_tier', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('secrets', 'trust_tier')
    # ### end Alembic commands ###
