apiVersion: builtin
kind: PatchTransformer
metadata:
  name: boxxkite-prod-cluster-scope
patch: |-
  - op: remove
    path: /metadata/namespace
target:
  group: admissionregistration.k8s.io
  version: v1
  kind: ValidatingAdmissionPolicy
  name: boxxkite-prod-sandbox-pod-hardening
